name: Build

on:
  issues:
    types: [opened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Package install
      run: |
        yarn install
    - name: Update the Content
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      id: update-content
      run: |
        labels=$(echo "$GITHUB_CONTEXT" | jq '.event.issue.labels[].name')
        SLUG=$(node ./contentUpdater/index.js "${{ github.event.action }}" "${{ github.event.issue.html_url }}" "${{ github.event.issue.title }}" "${labels}" "${{ github.event.issue.body }}")
        echo "::set-output name=SLUG::$SLUG"

        git config --global user.email "you@example.com"
        git config --global user.name "Marvin"
        git add .
        git commit -m "update content"
        git push
    - name: Build
      run: |
        yarn run build
    - name: Deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/macabeus/ryujinx-catalog.git
        yarn run deploy
    - name: Add comment on issue
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.issue.number }}
        body: |
          Deployed 🚀
          Checkout at [${{ steps.update-content.outputs.SLUG }}](https://macabeus.github.io/ryujinx-catalog/game/${{ steps.update-content.outputs.SLUG }})
